name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Create app dir on VM and clean old code
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
            "mkdir -p ~/app-directory && cd ~/app-directory && docker compose down || true && rm -rf *"

      - name: Upload files to VM
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/app-directory/

      - name: Start app on VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
            "cd ~/app-directory && docker compose up -d --build"
